// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import "dotenv/config";

const dbFile = process.env["DB_FILE"] ?? "db.sqlite";
console.log("Using database file:", dbFile);

export default defineConfig({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "./prisma/migrations",
  },
  datasource: {
    url: `file:${dbFile}`,
  },
});
