// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { getArguments } from "./utils.ts";


const { dbFile } = getArguments()
console.log('Using database file:', dbFile)

export default defineConfig({
  schema: "../prisma/schema.prisma",
  migrations: {
    path: "../prisma/migrations",
  },
  datasource: {
    url: `file:${dbFile}`,
  },
});
